### ISSUE TITLE
'No such file or directory' if application is missing the templates dir

### ISSUE THREAD

**Issue by tigarmo** [canonical/craft-application#546]
### Bug Description

I have an admittedly dev version of Rockcraft here that is using the new InitCommand but has no templates.

### To Reproduce

Run `toolcraft init` where `toolcraft` has no `templates` dir

### Relevant log output

```shell
❯ rockcraft init
rockcraft internal error: FileNotFoundError(2, 'No such file or directory')
Full execution log: '/home/tiago/.local/state/rockcraft/log/rockcraft-20241024-091607.807534.log'
Traceback (most recent call last):
  File "/snap/rockcraft/x1/lib/python3.10/site-packages/craft_application/application.py", line 600, in run
    return_code = self._run_inner()
  File "/snap/rockcraft/x1/lib/python3.10/site-packages/craft_application/application.py", line 550, in _run_inner
    dispatcher.load_command(self.app_config),
  File "/snap/rockcraft/x1/lib/python3.10/site-packages/craft_cli/dispatcher.py", line 246, in load_command
    self._loaded_command.fill_parser(parser)
  File "/snap/rockcraft/x1/lib/python3.10/site-packages/craft_application/commands/init.py", line 79, in fill_parser
    choices=self.profiles,
  File "/snap/rockcraft/x1/lib/python3.10/site-packages/craft_application/commands/init.py", line 98, in profiles
    template_dirs = [
  File "/snap/rockcraft/x1/lib/python3.10/site-packages/craft_application/commands/init.py", line 98, in <listcomp>
    template_dirs = [
  File "/snap/rockcraft/x1/usr/lib/python3.10/pathlib.py", line 1017, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/snap/rockcraft/x1/lib/python3.10/site-packages/rockcraft/templates'
```

**Comment by mr-cal** [comment]
From planning yesterday, we (@sergiusens and I) aren't convinced that this needs to be fixed.

We think that creating a default template is a required implementation task for the developer of an application.

**Comment by lengau** [comment]
I'd prefer if we make the error message more useful to the developer.

**Comment by mr-cal** [comment]
I think that's a good compromise and a quick improvement.
